const wordsList = [
  {
    id: '5e9f5ee35eb9e72bc21afe8c',
    group: 4,
    page: 7,
    word: 'access',
    image: 'files/08_2541.jpg',
    audio: 'files/08_2541.mp3',
    audioMeaning: 'files/08_2541_meaning.mp3',
    audioExample: 'files/08_2541_example.mp3',
    textMeaning: '<i>Access</i> is the right to enter or use something.',
    textExample: 'The manager was the only person with <b>access</b> to the password.',
    transcription: '[ǽkses]',
    textExampleTranslate: 'Менеджер был единственным человеком, имеющим доступ к паролю',
    textMeaningTranslate: 'Доступ - это право вводить или использовать что-либо',
    wordTranslate: 'доступ',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe8d',
    group: 4,
    page: 7,
    word: 'conduct',
    image: 'files/08_2542.jpg',
    audio: 'files/08_2542.mp3',
    audioMeaning: 'files/08_2542_meaning.mp3',
    audioExample: 'files/08_2542_example.mp3',
    textMeaning: '<i>Conduct</i> is the way that someone acts.',
    textExample: 'She was punished for her bad <b>conduct</b>.',
    transcription: '[kɑ́ndʌkt]',
    textExampleTranslate: 'Она была наказана за плохое поведение',
    textMeaningTranslate: 'Поведение - это способ, которым кто-то действует',
    wordTranslate: 'поведение',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe8e',
    group: 4,
    page: 7,
    word: 'constant',
    image: 'files/08_2543.jpg',
    audio: 'files/08_2543.mp3',
    audioMeaning: 'files/08_2543_meaning.mp3',
    audioExample: 'files/08_2543_example.mp3',
    textMeaning: 'When an event or action is <i>constant</i>, it happens a lot or all of the time.',
    textExample: 'The television at home is in <b>constant</b> use.',
    transcription: '[kɑ́nstənt]',
    textExampleTranslate: 'Телевидение дома постоянно используется',
    textMeaningTranslate: 'Когда событие или действие является постоянным, это происходит много или все время',
    wordTranslate: 'константа',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe8f',
    group: 4,
    page: 7,
    word: 'crack',
    image: 'files/08_2544.jpg',
    audio: 'files/08_2544.mp3',
    audioMeaning: 'files/08_2544_meaning.mp3',
    audioExample: 'files/08_2544_example.mp3',
    textMeaning: 'A <i>crack</i> is a narrow space between the parts of something broken.',
    textExample: 'The old window was covered with <b>cracks</b>.',
    transcription: '[kræk]',
    textExampleTranslate: 'Старое окно было покрыто трещинами',
    textMeaningTranslate: 'Трещина - это узкое пространство между частями чего-то сломанного',
    wordTranslate: 'трещины',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe90',
    group: 4,
    page: 7,
    word: 'device',
    image: 'files/08_2545.jpg',
    audio: 'files/08_2545.mp3',
    audioMeaning: 'files/08_2545_meaning.mp3',
    audioExample: 'files/08_2545_example.mp3',
    textMeaning: 'A <i>device</i> is an object or a machine.',
    textExample: 'A thermometer is a <b>device</b> that tells temperature.',
    transcription: '[diváis]',
    textExampleTranslate: 'Термометр - это устройство, которое сообщает температуру',
    textMeaningTranslate: 'Устройство - это объект или машина',
    wordTranslate: 'устройство',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe91',
    group: 4,
    page: 7,
    word: 'enclose',
    image: 'files/08_2546.jpg',
    audio: 'files/08_2546.mp3',
    audioMeaning: 'files/08_2546_meaning.mp3',
    audioExample: 'files/08_2546_example.mp3',
    textMeaning: 'To <i>enclose</i> something is to contain it.',
    textExample: 'The cows in the field were <b>enclosed</b> by a fence.',
    transcription: '[inklóuz]',
    textExampleTranslate: 'Коровы в поле были огорожены забором',
    textMeaningTranslate: 'Вложить что-то - значит содержать это',
    wordTranslate: 'вложить',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe92',
    group: 4,
    page: 7,
    word: 'grip',
    image: 'files/08_2547.jpg',
    audio: 'files/08_2547.mp3',
    audioMeaning: 'files/08_2547_meaning.mp3',
    audioExample: 'files/08_2547_example.mp3',
    textMeaning: 'To <i>grip</i> something is to hold it very tightly.',
    textExample: 'I was scared, so I <b>gripped</b> my older sister’s hand.',
    transcription: '[grip]',
    textExampleTranslate: 'Я был напуган, поэтому я схватил руку моей старшей сестры',
    textMeaningTranslate: 'Захватить что-то - значит держать это очень крепко',
    wordTranslate: 'рукоятка',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe93',
    group: 4,
    page: 7,
    word: 'halt',
    image: 'files/08_2548.jpg',
    audio: 'files/08_2548.mp3',
    audioMeaning: 'files/08_2548_meaning.mp3',
    audioExample: 'files/08_2548_example.mp3',
    textMeaning: 'To <i>halt</i> is to stop moving.',
    textExample: 'The criminal <b>halted</b> when he saw the police coming.',
    transcription: '[hɔːlt]',
    textExampleTranslate: 'Преступник остановился, когда увидел, как идет полиция',
    textMeaningTranslate: 'Остановить - значит перестать двигаться',
    wordTranslate: 'хромать',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe94',
    group: 4,
    page: 7,
    word: 'impending',
    image: 'files/08_2549.jpg',
    audio: 'files/08_2549.mp3',
    audioMeaning: 'files/08_2549_meaning.mp3',
    audioExample: 'files/08_2549_example.mp3',
    textMeaning: 'If something is <i>impending</i>, it is going to happen soon.',
    textExample: 'The student was nervous about her <b>impending</b> test.',
    transcription: '[impéndiŋ]',
    textExampleTranslate: 'Студент нервничал по поводу ее предстоящего теста',
    textMeaningTranslate: 'Если что-то надвигается, это скоро случится',
    wordTranslate: 'надвигающийся',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe95',
    group: 4,
    page: 7,
    word: 'influence',
    image: 'files/08_2550.jpg',
    audio: 'files/08_2550.mp3',
    audioMeaning: 'files/08_2550_meaning.mp3',
    audioExample: 'files/08_2550_example.mp3',
    textMeaning: 'To <i>influence</i> someone or something is to have an effect on them.',
    textExample: 'My friend <b>influenced</b> my decision to attend Terrance University.',
    transcription: '[ínfuəns]',
    textExampleTranslate: 'Мой друг повлиял на мое решение учиться в университете Терранс',
    textMeaningTranslate: 'Влиять на кого-то или что-то значит влиять на них',
    wordTranslate: 'оказывать влияние',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe96',
    group: 4,
    page: 7,
    word: 'law',
    image: 'files/08_2551.jpg',
    audio: 'files/08_2551.mp3',
    audioMeaning: 'files/08_2551_meaning.mp3',
    audioExample: 'files/08_2551_example.mp3',
    textMeaning: 'A <i>law</i> is a rule made by the legislative body.',
    textExample: 'The students learned about different <b>laws</b> during social studies class.',
    transcription: '[lɔː]',
    textExampleTranslate: 'Студенты узнали о различных законах на уроках обществознания',
    textMeaningTranslate: 'Закон - это норма законодательного органа',
    wordTranslate: 'закон',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe97',
    group: 4,
    page: 7,
    word: 'mode',
    image: 'files/08_2552.jpg',
    audio: 'files/08_2552.mp3',
    audioMeaning: 'files/08_2552_meaning.mp3',
    audioExample: 'files/08_2552_example.mp3',
    textMeaning: 'A <i>mode</i> is a setting or condition on a machine.',
    textExample: 'Melissa turned the TV to quiet <b>mode</b> while she talked on the phone.',
    transcription: '[moud]',
    textExampleTranslate: 'Мелисса переключила телевизор в тихий режим, пока говорила по телефону',
    textMeaningTranslate: 'Режим - это настройка или условие на машине',
    wordTranslate: 'режим',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe98',
    group: 4,
    page: 7,
    word: 'perspire',
    image: 'files/08_2553.jpg',
    audio: 'files/08_2553.mp3',
    audioMeaning: 'files/08_2553_meaning.mp3',
    audioExample: 'files/08_2553_example.mp3',
    textMeaning: 'To <i>perspire</i> means to sweat.',
    textExample: 'I usually <b>perspire</b> a lot when I am at athletics practice.',
    transcription: '[pərspáiər]',
    textExampleTranslate: 'Я обычно сильно потею, когда занимаюсь легкой атлетикой',
    textMeaningTranslate: 'Потеть значит потеть',
    wordTranslate: 'потеть',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe99',
    group: 4,
    page: 7,
    word: 'replace',
    image: 'files/08_2554.jpg',
    audio: 'files/08_2554.mp3',
    audioMeaning: 'files/08_2554_meaning.mp3',
    audioExample: 'files/08_2554_example.mp3',
    textMeaning: 'To <i>replace</i> something is to put it in the place of something else.',
    textExample: 'I <b>replaced</b> the tire on my car because it was flat.',
    transcription: '[ripléis]',
    textExampleTranslate: 'Я заменил шину на моей машине, потому что она была плоской',
    textMeaningTranslate: 'Заменить что-то - значит поставить это вместо чего-то другого',
    wordTranslate: 'заменить',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9a',
    group: 4,
    page: 7,
    word: 'snap',
    image: 'files/08_2555.jpg',
    audio: 'files/08_2555.mp3',
    audioMeaning: 'files/08_2555_meaning.mp3',
    audioExample: 'files/08_2555_example.mp3',
    textMeaning: 'To <i>snap</i> something means to break it suddenly, which can cause a loud noise.',
    textExample: 'I took the drumstick and <b>snapped</b> it with my hands.',
    transcription: '[snæp]',
    textExampleTranslate: 'Я взял голень и защелкнул его руками',
    textMeaningTranslate: 'Взломать что-то значит внезапно сломать, что может вызвать громкий шум',
    wordTranslate: 'щелчок',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9b',
    group: 4,
    page: 7,
    word: 'sly',
    image: 'files/08_2556.jpg',
    audio: 'files/08_2556.mp3',
    audioMeaning: 'files/08_2556_meaning.mp3',
    audioExample: 'files/08_2556_example.mp3',
    textMeaning: 'If a person or animal is <i>sly</i>, they are sneaky or good at tricking people.',
    textExample: 'The <b>sly</b> fox stole the eggs from the nest.',
    transcription: '[slai]',
    textExampleTranslate: 'Хитрая лиса украла яйца из гнезда',
    textMeaningTranslate: 'Если человек или животное хитрые, они подлые или умные обманывают людей',
    wordTranslate: 'втихаря',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9c',
    group: 4,
    page: 7,
    word: 'tend',
    image: 'files/08_2557.jpg',
    audio: 'files/08_2557.mp3',
    audioMeaning: 'files/08_2557_meaning.mp3',
    audioExample: 'files/08_2557_example.mp3',
    textMeaning: 'To <i>tend</i> to do something is to be likely to do it or to do it often.',
    textExample: 'My mom <b>tends</b> to buy me the perfect gift each Christmas.',
    transcription: '[tend]',
    textExampleTranslate: 'Моя мама покупает мне идеальный подарок каждое Рождество',
    textMeaningTranslate: 'Быть склонным к тому, чтобы что-то делать, значит быть способным делать это часто или делать это часто',
    wordTranslate: 'как правило',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9d',
    group: 4,
    page: 7,
    word: 'valid',
    image: 'files/08_2558.jpg',
    audio: 'files/08_2558.mp3',
    audioMeaning: 'files/08_2558_meaning.mp3',
    audioExample: 'files/08_2558_example.mp3',
    textMeaning: 'When something is <i>valid</i>, it is correct or based on good reasoning.',
    textExample: 'The expert’s opinion on the subject was more <b>valid</b> than others.',
    transcription: '[vǽlid]',
    textExampleTranslate: 'Мнение эксперта по этому вопросу было более обоснованным, чем у других',
    textMeaningTranslate: 'Когда что-то действительно, это правильно или основано на здравом рассуждении',
    wordTranslate: 'действительный',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9e',
    group: 4,
    page: 7,
    word: 'version',
    image: 'files/08_2559.jpg',
    audio: 'files/08_2559.mp3',
    audioMeaning: 'files/08_2559_meaning.mp3',
    audioExample: 'files/08_2559_example.mp3',
    textMeaning: 'A <i>version</i> is an account of something that differs slightly from the original.',
    textExample: 'She read the students British <b>version</b> of the Chinese fairy tale.',
    transcription: '[və́ːrʒən]',
    textExampleTranslate: 'Она читала студентам британскую версию китайской сказки',
    textMeaningTranslate: 'Версия - это отчет о чем-то, что немного отличается от оригинала',
    wordTranslate: 'версия',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe9f',
    group: 4,
    page: 7,
    word: 'whatsoever',
    image: 'files/08_2560.jpg',
    audio: 'files/08_2560.mp3',
    audioMeaning: 'files/08_2560_meaning.mp3',
    audioExample: 'files/08_2560_example.mp3',
    textMeaning: 'You use <i>whatsoever</i> after a noun to emphasize that there is nothing of that thing.',
    textExample: 'The boy had no idea <b>whatsoever</b> how to finish the story.',
    transcription: '[wὰtsouévər]',
    textExampleTranslate: 'Мальчик понятия не имел, как закончить историю',
    textMeaningTranslate: 'Вы используете что угодно после существительного, чтобы подчеркнуть, что ничего этого нет',
    wordTranslate: 'вообще',
  },
];
export default wordsList;
